AWSTemplateFormatVersion: 2010-09-09
Description: AWS Migration Hub Refactor Spaces foundation stack for the Application Modernization Workshop/ Immersion Day

Parameters:
  imageshopVpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: imageshopVpcId

  imageshopBackendDnsName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: imageshopPublicDnsName

Resources:
  imageshopRefactorSpacesModernizationEnvironment:
    Type: AWS::RefactorSpaces::Environment
    Properties:
      Name: unistore-dev
      NetworkFabricType: TRANSIT_GATEWAY
      Description: A Refactor Spaces environment for the Unicorn store

  imageshopRefactorSpacesApplication:
    Type: AWS::RefactorSpaces::Application
    Properties:
      Name: unistore
      EnvironmentIdentifier: !Ref imageshopRefactorSpacesModernizationEnvironment
      VpcId: !Ref imageshopVpcId
      ProxyType: API_GATEWAY
      ApiGatewayProxy:
        EndpointType: REGIONAL
      
  imageshopLegacyService:
    Type: AWS::RefactorSpaces::Service
    Properties:
      Name: legacy
      EnvironmentIdentifier: !Ref imageshopRefactorSpacesModernizationEnvironment
      ApplicationIdentifier: !GetAtt imageshopRefactorSpacesApplication.ApplicationIdentifier
      EndpointType: URL
      VpcId: !Ref imageshopVpcId
      UrlEndpoint:
        Url: !Ref imageshopBackendDnsName
        HealthUrl: !Join [ "", [ !Ref imageshopBackendDnsName, '/actuator/health' ] ]

  imageshopDefaultRoute:
    Type: AWS::RefactorSpaces::Route
    Properties:
      RouteType: DEFAULT
      ServiceIdentifier: !GetAtt imageshopLegacyService.ServiceIdentifier
      EnvironmentIdentifier: !Ref imageshopRefactorSpacesModernizationEnvironment
      ApplicationIdentifier: !GetAtt imageshopRefactorSpacesApplication.ApplicationIdentifier

  imageshopEnvironmentIdSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: imageshopEnvironmentId
      Value: !GetAtt imageshopRefactorSpacesModernizationEnvironment.EnvironmentIdentifier
      Type: String
      Description: imageshop Application Id

  imageshopApplicationIdSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: imageshopApplicationId
      Value: !GetAtt imageshopRefactorSpacesApplication.ApplicationIdentifier
      Type: String
      Description: imageshop Environment Id

  imageshopApiGatewayIdSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: imageshopApiGatewayId
      Value: !GetAtt imageshopRefactorSpacesApplication.ApiGatewayId
      Type: String
      Description: imageshop API Gateway Id

Outputs:
  imageshopApiGatewayProxyUrl:
    Value: !GetAtt imageshopRefactorSpacesApplication.ProxyUrl